services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        image: x-webhook-receiver
        container_name: x-webhook-receiver
        environment:
            - PORT=3000
            # Configure data directory to match volume mount
            - DATA_DIR=/app/data
